### ISSUE TITLE
[BUG] Pose /lay and others not working on MC 1.17.1

### ISSUE THREAD

**Issue by Disguys** [StumpStudio/PosePlugin#7]
**Describe the bug**
command `/lay` warnings

**To Reproduce**
1. Send `/lay`

**Plugin version:**
PosePlugin-4.0-Beta-1

**Server software**
Airplane 1.17.1 build 45

**Console log**
```
[Mon, 12. Jul 2021 12:59:33 UTC INFO] LinKs_QQ issued server command: /lay
[Mon, 12. Jul 2021 12:59:33 UTC WARN] java.lang.reflect.InvocationTargetException
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.api.poses.PoseBuilder.build(PoseBuilder.java:40)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.plugin.commands.PoseCommandGenerator.lambda$generatePoseCommands$4(PoseCommandGenerator.java:63)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.plugin.commands.SimpleCommand.lambda$new$1(SimpleCommand.java:39)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2243)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2035)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1407)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1385)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1378)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1354)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1265)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/java.lang.Thread.run(Thread.java:831)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] Caused by: java.lang.reflect.InvocationTargetException
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.api.utils.nms.ToolFactory.create(ToolFactory.java:71)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.api.poses.seatrequiring.LayPose.<init>(LayPose.java:23)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] ... 30 more
[Mon, 12. Jul 2021 12:59:33 UTC WARN] Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)'
[Mon, 12. Jul 2021 12:59:33 UTC WARN] at ru.armagidon.poseplugin.api.utils.nms.v1_17.npc.FakePlayer117.<init>(FakePlayer117.java:122)
[Mon, 12. Jul 2021 12:59:33 UTC WARN] ... 37 more
```

**Comment by Disguys** [comment]
The following poses also do not work: `/handshake`, `/clap`, `/point`, `/spinjitsu`, `/wave`.
Causes errors similar to `/lay`.
logs
```
[01:30:43 INFO]: Disguys issued server command: /spinjitsu
[01:30:43 WARN]: java.lang.reflect.InvocationTargetException
[01:30:43 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:30:43 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[01:30:43 WARN]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:30:43 WARN]: at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[01:30:43 WARN]: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[01:30:43 WARN]: at ru.armagidon.poseplugin.api.poses.PoseBuilder.build(PoseBuilder.java:40)
[01:30:43 WARN]: at ru.armagidon.poseplugin.plugin.commands.PoseCommandGenerator.lambda$generatePoseCommands$4(PoseCommandGenerator.java:63)
[01:30:43 WARN]: at ru.armagidon.poseplugin.plugin.commands.SimpleCommand.lambda$new$1(SimpleCommand.java:39)
[01:30:43 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:30:43 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[01:30:43 WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[01:30:43 WARN]: at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:819)
[01:30:43 WARN]: at org.bukkit.command.FormattedCommandAlias.execute(FormattedCommandAlias.java:37)
[01:30:43 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[01:30:43 WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[01:30:43 WARN]: at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2248)
[01:30:43 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2059)
[01:30:43 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2040)
[01:30:43 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[01:30:43 WARN]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[01:30:43 WARN]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[01:30:43 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:30:43 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[01:30:43 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[01:30:43 WARN]: at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1407)
[01:30:43 WARN]: at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[01:30:43 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[01:30:43 WARN]: at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1385)
[01:30:43 WARN]: at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1378)
[01:30:43 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[01:30:43 WARN]: at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1354)
[01:30:43 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1265)
[01:30:43 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[01:30:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
[01:30:43 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[01:30:43 WARN]: at jdk.internal.reflect.GeneratedConstructorAccessor50.newInstance(Unknown Source)
[01:30:43 WARN]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:30:43 WARN]: at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[01:30:43 WARN]: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[01:30:43 WARN]: at ru.armagidon.poseplugin.api.utils.nms.ToolFactory.create(ToolFactory.java:71)
[01:30:43 WARN]: at ru.armagidon.poseplugin.api.poses.experimental.SpinJitsuPose.<init>(SpinJitsuPose.java:36)
[01:30:43 WARN]: ... 34 more
[01:30:43 WARN]: Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)'
[01:30:43 WARN]: at ru.armagidon.poseplugin.api.utils.nms.v1_17.npc.FakePlayer117.<init>(FakePlayer117.java:122)
[01:30:43 WARN]: ... 40 more
```
